function [structure] = PRM_lattice(structure)

% Convert lattice parameters from matrix to distances and angles

structure.cell_parameters=[...
    sqrt(power(structure.lattice(1,1),2)+power(structure.lattice(2,1),2)+power(structure.lattice(3,1),2)),...
    sqrt(power(structure.lattice(1,2),2)+power(structure.lattice(2,2),2)+power(structure.lattice(3,2),2)),...
    sqrt(power(structure.lattice(1,3),2)+power(structure.lattice(2,3),2)+power(structure.lattice(3,3),2))];

structure.cell_angles=[...
    acosd((structure.lattice(1,2)*structure.lattice(1,3)+...
    structure.lattice(2,2)*structure.lattice(2,3)+...
    structure.lattice(3,2)*structure.lattice(3,3))...
    /(structure.cell_parameters(2)*structure.cell_parameters(3))),...
    ...
    acosd((structure.lattice(1,1)*structure.lattice(1,3)+...
    structure.lattice(2,1)*structure.lattice(2,3)+...
    structure.lattice(3,1)*structure.lattice(3,3))...
    /(structure.cell_parameters(1)*structure.cell_parameters(3))),...
    ...
    acosd((structure.lattice(1,2)*structure.lattice(1,3)+...
    structure.lattice(2,2)*structure.lattice(2,3)+...
    structure.lattice(3,2)*structure.lattice(3,3))...
    /(structure.cell_parameters(2)*structure.cell_parameters(3)))];


end

